#!/bin/bash
set -o nounset
set -o errexit
# Initialize crystal app
app_name=$1
crystal init app $app_name
cd $app_name
# Delete the default Projectfile
rm Projectfile
# Add amethyst and other required dependencies to Projectfile
cat > Projectfile <<-Deps
  deps do
    github "Codcore/amethyst"
    github "spalger/crystal-mime"

    # TODO - Add ORM
    github "manastech/crystal-sqlite3"
  end
Deps
# Fetch the dependencies
crystal deps
## Create views and controllers folders
mkdir app
mkdir app/assets
mkdir app/assets/javascripts
mkdir app/assets/stylesheets
mkdir app/controllers
mkdir app/models
mkdir app/views

mkdir config
mkdir db
mkdir db/migrate
mkdir docs
mkdir public
mkdir scripts

#Create database.yml
cat > config/database.yml <<EOF
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
EOF

# development log
mkdir logs
cat > logs/development.log <<EOF
  use Amethyst::Middleware::ShowExceptions
  use Amethyst::Middleware::HttpLogger
  use Amethyst::Middleware::TimeLogger
  use Amethyst::Middleware::Session
  use Amethyst::Middleware::Static
EOF

# Remove the default crystal src file
rm src/$app_name.cr
touch src/$app_name.cr
# Class name needs to be capitalized
class_name="$(tr '[:lower:]' '[:upper:]' <<< ${app_name:0:1})${app_name:1}"
class_name+="App"

module $class_name
  class Application < Base::App

    settings.configure do |conf|
      conf.environment = "development"
      conf.static_dirs = ["/public"]
    end

    routes.draw do
      #Here define your routes
      #all "/", "welcome#index"
    end

    #register WelcomeController
   end
end

app = $class_name.new
app.serve
App
