#!/bin/bash
set -o nounset
set -o errexit
# Initialize crystal app
app_name=$1
crystal init app $app_name
cd $app_name
# Delete the default Projectfile
rm Projectfile
# Add amethyst and other required dependencies to Projectfile
cat > Projectfile <<-Deps
  deps do
    github "Codcore/amethyst"
    github "spalger/crystal-mime"
  end
Deps
# Fetch the dependencies
crystal deps
# Create views and controllers folders
mkdir src/$app_name/views
mkdir src/$app_name/controllers
# Remove the default crystal src file
rm src/$app_name.cr
touch src/$app_name.cr
# Class name needs to be capitalized
class_name="$(tr '[:lower:]' '[:upper:]' <<< ${app_name:0:1})${app_name:1}"
class_name+="App"
# Create base app with given name under src/app_name.cr
cat > src/$app_name.cr <<- App
require "amethyst"
class $class_name < Base::App
  routes.draw do
    # Here you define your routes e.g
    # get '/hello', "world#hello"
  end
end
app = $class_name.new
app.serve
App
